/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package classes;

import javax.swing.ImageIcon;

/**
 *
 * @author thayrone
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAkinator = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblResporta = new javax.swing.JLabel();
        lblBalao = new javax.swing.JLabel();
        btnAdivinha = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAkinator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/akinator.png"))); // NOI18N
        getContentPane().add(lblAkinator, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 157, 235, 410));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Adivinhe o Numero que estou pensando!");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 37, -1, -1));

        lblResporta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblResporta.setText("Sua resposta");
        getContentPane().add(lblResporta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        lblBalao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblBalao.setForeground(new java.awt.Color(0, 0, 0));
        lblBalao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBalao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/balao.png"))); // NOI18N
        lblBalao.setText("<html>Estou pensando em um <p> numero aleatório entre <strong>1</strong> e <strong>10</strong></p></html");
        lblBalao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblBalao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, -1, -1));

        btnAdivinha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdivinha.setText("Adivinhar");
        btnAdivinha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdivinhaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdivinha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));
        getContentPane().add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdivinhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdivinhaActionPerformed
        // TODO add your handling code here:
        double rdn = Math.random();
        int n= (int) (1+rdn*(10-1));
        int chute = (int) jSpinner1.getValue();
        String resposta = n==chute?"<html>Sua resposta está: <strong>Correta</strong></html>":"Que pena, eu estava pensando em: "+Integer.toString(n);
        lblBalao.setText(resposta);
    }//GEN-LAST:event_btnAdivinhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdivinha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblAkinator;
    private javax.swing.JLabel lblBalao;
    private javax.swing.JLabel lblResporta;
    // End of variables declaration//GEN-END:variables
}
